version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeep-backend
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    restart: unless-stopped
    env_file:
      - .env
