name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Trigger on pushes to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Add DOCKER_USERNAME secret in GitHub
          password: ${{ secrets.DOCKER_PASSWORD }} # Add DOCKER_PASSWORD secret in GitHub

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: 
          # docker build --target build -t my-image:build .

          docker build -t backoffice-be:prod .

      # Step 4: Push the Docker image
      - name: Push Docker Image
        run: |
          docker tag backoffice-be:prod infracdo/backoffice-be:prod
          docker push infracdo/backoffice-be:prod
